"""inicio

Revision ID: 334cf8dfebed
Revises: 
Create Date: 2024-06-21 22:00:13.922043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334cf8dfebed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permiso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('recurso', sa.String(), nullable=False),
    sa.Column('acceso', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permiso')),
    sa.UniqueConstraint('nombre', name=op.f('uq_permiso_nombre'))
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rol')),
    sa.UniqueConstraint('nombre', name=op.f('uq_rol_nombre'))
    )
    op.create_table('wallet_contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet_contract'))
    )
    op.create_table('rol_permiso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.Column('permiso_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permiso_id'], ['permiso.id'], name=op.f('fk_rol_permiso_permiso_id_permiso')),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], name=op.f('fk_rol_permiso_rol_id_rol')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rol_permiso'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], name=op.f('fk_user_rol_id_rol')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('coin', sa.String(length=5), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('transactions', sa.String(length=10), nullable=False),
    sa.Column('wallet_contract_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wallet_contract_id'], ['wallet_contract.id'], name=op.f('fk_wallet_wallet_contract_id_wallet_contract')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet'))
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nature', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('to', sa.String(length=50), nullable=False),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], name=op.f('fk_transaction_wallet_id_wallet')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction'))
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=True),
    sa.Column('apellido', sa.String(length=30), nullable=True),
    sa.Column('direccion', sa.String(length=50), nullable=True),
    sa.Column('ciudad', sa.String(length=50), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_profile_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profile'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    op.drop_table('transaction')
    op.drop_table('wallet')
    op.drop_table('user')
    op.drop_table('rol_permiso')
    op.drop_table('wallet_contract')
    op.drop_table('rol')
    op.drop_table('permiso')
    # ### end Alembic commands ###
