"""transaccion - campo fecha 

Revision ID: d7ef22f643f3
Revises: 334cf8dfebed
Create Date: 2024-07-08 20:21:53.014780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ef22f643f3'
down_revision = '334cf8dfebed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
