"""transaccion - campos no obligatorios

Revision ID: ec002237e7f8
Revises: d7ef22f643f3
Create Date: 2024-07-08 20:54:29.355256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec002237e7f8'
down_revision = 'd7ef22f643f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('to',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('confirmations',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('confirmations',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('to',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
